### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by desertlightning** [JohnRipper/QuantumJump#5]
I get this error when attempting to start the program,

**Comment by Technetium1** [comment]
@desertlightning On newest commit? Which os/python? Have you created a config?

**Comment by desertlightning** [comment]
I got it to work, I run Raspbian. I believe it was just since it didn't have python 3.8 already.

**Comment by desertlightning** [comment]
Nevermind I didn't realize it automatically generates a config
