### ISSUE TITLE
Youtube URL's work, but not the title

### ISSUE THREAD

**Issue by desertlightning** [JohnRipper/QuantumJump#6]
I can post yt (URL) and get the video but if I use the title it will not load video

**Comment by JohnRipper** [comment]
Submitting a potential fix today that should help.  

I set up the bot to use up to 2 search methods but with the same command.
If Google api key is provided it will attempt a search with Google. If you run out of your 100 free search limit then it will attempt to use duck duck go to find a working song.  You don't need a Google api key for the command to work though, it will just use duckduckgo if all you do is update the module.  

A break down of the differences between the two. 

Fix 1. google api 
     needs a working api key from https://console.developers.google.com/, under api -> credentials.
     standard quota limit is 100 searches a day. 
     old code for it is still around just need to test it

Fix 2. duck duck go api. 
     Coesnt need api key
     Unlimited daily rate limit, but there seems to be a small one that resets every few minutes. 
     New code that also needs testing and being added to the repo today!

**Comment by Technetium1** [comment]
@desertlightning I can confirm this is a functional fix :)
